springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: '/${application.name}-docs'
  pathsToMatch: /v*/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    logfile:
      external-file: '~/logs/${application.name:spring-boot-app}.log'

logging:
  file:
    name: '~/logs/${application.name:spring-boot-app}.log'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    initialInstanceInfoReplicationIntervalSeconds: 10
    registryFetchIntervalSeconds: 30 # our services are not that dynamic to need less than the default 30s
  instance:
    ipAddress: '${HOST_IP:127.0.0.1}'
    nonSecurePort: '${server.port}'
    preferIpAddress: true
    instanceId: '${HOST_IP:127.0.0.1}:${server.port}'
    healthCheckUrl: 'http://${HOST_IP:127.0.0.1}:${server.port}/actuator/health'
    metadataMap:
      management:
        context-path: '/actuator'
        port: '${server.port}'