server:
  servlet:
    context-path: ''

springdoc:
  swagger-ui:
    path: /docs

management:
  endpoints:
    web:
      exposure:
        include: *

eureka:
  instance:
    ipAddress: '${HOST_IP:127.0.0.1}'
    nonSecurePort: '${server.port}'
    preferIpAddress: true
    instanceId: '${HOST_IP:127.0.0.1}:${server.port}'
    healthCheckUrl: 'http://${HOST_IP:127.0.0.1}:${server.port}${server.servlet.context-path}/actuator/health'
    metadataMap:
      management:
        context-path: '${server.servlet.context-path}/actuator'
        port: '${server.port}'