logging:
  file:
    name: '/var/log/${spring.application.name}.log'

eureka:
  instance:
    hostname: '${HOSTNAME}'
    preferIpAddress: false
    instanceId: '${eureka.instance.hostname}:${server.port}'
    homePageUrl: 'http://${eureka.instance.hostname}:${server.port}'
    healthCheckUrl: 'http://${eureka.instance.hostname}:${server.port}/actuator/health'
    metadataMap:
      management:
        context-path: /actuator
        port: ${server.port}
  client:
    serviceUrl:
      defaultZone: 'http://eureka:8761/eureka'