zuul:
  retryable: true # Enable retries on Zuul
  routes:
    hello-service:
      service-id: 'hello-service'
      path: '/v1/greeting**'
      strip-prefix: false
    weather-service:
      service-id: 'weather-service'
      path: '/v1/weather**'
      strip-prefix: false