server:
  port: 8761

eureka:
  environment: aws
  datacenter: cloud
  instance:
    preferIpAddress: false
    ipAddress: '${HOST_IP}'
    hostname: '${SERVICE_HOSTNAME}'
    instanceId: '${HOST_IP}:${server.port}'
    healthCheckUrl: 'http://${HOST_IP}:${server.port}/actuator/health'
    metadataMap:
      management:
        context-path: /actuator
        port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://eureka-1.internal:8761/eureka/eureka,http://eureka-2.internal:8761/eureka/eureka'
  server:
    enableSelfPreservation: false
    batchReplication: true
